tasks:
  - init: |
      yarn install
      yarn build
      mkdir /workspace/schedviz/traces
    command: |
      yarn bazel run server -- -- -storage_path="/workspace/schedviz/traces"
image:
  file: .gitpod.Dockerfile
